encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entryPage"),
    path("newEntry", views.newentry, name="newPage"),
    
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django import forms
import markdown2

from . import util



class editForm(forms.Form):#this is creating a form with from class with multiple field
    title = forms.CharField(label="Title")
    content = forms.CharField(widget=forms.Textarea)
        
            
       
def newentry(request):

    if request.method == 'POST':
        
        form = editForm(request.POST)

        if form.is_valid():

           title = form.cleaned_data["title"]

           content = form.cleaned_data["content"]

           util.save_entry(title,content)

           return HttpResponseRedirect(reverse("encyclopedia:index"))
   
        else:
            
            return render(request, "encyclopedia/newPage.html", {
            "form": form
            }) 
    
    return render(request, "encyclopedia/newPage.html", {
            "form": editForm()
            })  

def editpage(request):
    return None

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def entry(request, title):
    
    return render(request,"encyclopedia/EntryPage.html",{# Here, I converted md file to html
        "page": markdown2.markdown(util.get_entry(title)),
        "entry_title": title #I got page title  with this variable that i used in entrypage.html to display title name of page.
        })
    

def search(request):
     
    if request.method == 'POST':
        search_info = 'POST'


   
  
      
        

    

    
     

encyclopedia/templates/encyclopedia/EntryPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
   {{ entry_title }}
{% endblock %}

{# in views.py, i created a function called entry from taking entry by it's title using utility function called get_entry(); "wiki/<str:title> in url.py in path field" #}

{% block body %}
    
        {{ page|safe }}
  
        <a href="editpage.html">Edit page</a>

        {% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
          <a href="{% url 'encyclopedia:entryPage' entry %}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>
 
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form>
                    <input action="#" method="POST" class="search" type="text" name="title" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                  <a href="{% url 'encyclopedia:newPage' %}">Create New Page</a> 
                </div>
                <div>
                    Random Page
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    
    <form action="#" method="POST" name="newPage">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Save Entry">
    </form>
  
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
   
 
{% endblock %}